name: CI/CD

on:
  push:
    branches: [ master ]
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
     image: registry.gitlab.utu.fi/tech/soft/thesis/builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: | 
          cd latex
          ls -a
          latexmk -pdf --shell-escape thesis.tex
      - name: validate
        run: pdfa-validate latex/thesis.pdf|grep '^PASS'
      - name: deploy
        run: |
          wget https://tech.utugit.fi/soft/tools/sitegen/sitegen.jar -O sitegen.jar
          java -jar sitegen.jar -pdfjs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
      - name: ls
        run: |
          ls -a
          cd public
          ls -a  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
