name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: registry.gitlab.utu.fi/tech/soft/thesis/builder:latest
    steps:
      - name: build
        run: cd latex |
         latexmk -pdf --shell-escape thesis.tex

