name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  # build latex/thesis.tex -> latex/thesis.pdf using pdflatex
  # shell-escape functionality is required by the minted package
  build:
    runs-on: ubuntu-latest
    container:
     image: registry.gitlab.utu.fi/tech/soft/thesis/builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: cd latex |
         latexmk -pdf --shell-escape thesis.tex
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: latex
          path: latex/thesis.pdf
      - name: validate
        run: pdfa-validate latex/thesis.pdf|grep '^PASS'
      - name: deploy
        run: wget https://tech.utugit.fi/soft/tools/sitegen/sitegen.jar -O sitegen.jar |
          java -jar sitegen.jar -pdfjs
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/
